development:
  password: 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
  theme_id: "108193808537"
  store: maui-86.myshopify.com
production:
  password: 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
  theme_id: "108808667287"
  store: maui-86-production.myshopify.com
  ignore_files:
  - config/settings_data.json
